# Generated by Django 5.2.6 on 2025-09-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=191, verbose_name='Pregunta')),
                ('correct_answer', models.CharField(max_length=191, verbose_name='Respuesta correcta')),
                ('false_answer_1', models.CharField(max_length=191, verbose_name='Respuesta falsa')),
                ('false_answer_2', models.CharField(max_length=191, verbose_name='Respuesta falsa')),
                ('false_answer_3', models.CharField(max_length=191, verbose_name='Respuesta falsa')),
                ('question_info', models.TextField(verbose_name='Informacion adicional')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
