# Generated by Django 5.2.6 on 2025-09-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='user_id',
            new_name='user',
        ),
    ]
