# Generated by Django 5.2.6 on 2025-09-28 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Dialogo',
                'verbose_name_plural': 'Dialogos',
                'db_table': 'dialogue_categories',
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dialogue', models.TextField(default='...', verbose_name='Dialogo')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.game')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.dialoguecategory')),
            ],
            options={
                'verbose_name': 'Dialogo',
                'verbose_name_plural': 'Dialogos',
                'db_table': 'dialogues',
                'ordering': ['game__game_name'],
            },
        ),
    ]
