# Generated by Django 5.2.6 on 2025-09-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_rename_game_id_score_game_rename_user_id_score_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
