# Generated by Django 5.2.6 on 2025-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_dialoguecategory_dialogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialoguecategory',
            options={'verbose_name': 'Categoria de dialogo', 'verbose_name_plural': 'Categorias de dialogos'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'get_latest_by': 'date_played', 'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue',
            field=models.TextField(verbose_name='Dialogo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(verbose_name='Reglas'),
        ),
    ]
