# Generated by Django 5.2.6 on 2025-10-07 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_alter_dialoguecategory_options_alter_game_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.dialoguecategory', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue',
            field=models.TextField(unique=True, verbose_name='Dialogo'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.game', verbose_name='juego'),
        ),
        migrations.AlterField(
            model_name='score',
            name='date_played',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='GlobalRank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'global_rank',
                'ordering': ['-score'],
            },
        ),
    ]
