# Generated by Django 5.2.6 on 2025-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_alter_dialogue_category_alter_dialogue_dialogue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue',
            field=models.TextField(default='', null=True, verbose_name='Dialogo'),
        ),
        migrations.AlterField(
            model_name='dialoguecategory',
            name='category_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dialoguecategory',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(default='', null=True, verbose_name='Reglas'),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='globalrank',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
