# Generated by Django 5.2.6 on 2025-10-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_alter_dialogue_category_alter_dialogue_dialogue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=10, null=True, verbose_name='Usuario')),
                ('subject', models.CharField(default='', max_length=150, null=True, verbose_name='Asunto')),
                ('description', models.TextField(default='', null=True, verbose_name='Descripcion')),
                ('image_url', models.URLField(default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='dialogue',
            field=models.TextField(default='', null=True, verbose_name='Dialogo'),
        ),
        migrations.AlterField(
            model_name='dialoguecategory',
            name='category_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dialoguecategory',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules',
            field=models.TextField(default='', null=True, verbose_name='Reglas'),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='globalrank',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
