# Generated by Django 5.2.6 on 2025-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clicked_campaign',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
