# Generated by Django 5.2.6 on 2025-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordleWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=12, unique=True, verbose_name='Palabra')),
            ],
            options={
                'db_table': 'wordle_words',
            },
        ),
    ]
