# Generated by Django 5.2.6 on 2025-10-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordleword',
            options={'verbose_name': 'Palabra', 'verbose_name_plural': 'Palabras'},
        ),
    ]
